-- Creando la vista PREMIO (CHEF - REGISTRO - CLASIFICACION)
CREATE VIEW PREMIO AS
SELECT
	C.NOMBRE_CHEF,
	A.PLATO_POPULAR,
	G.PUESTO_CLASIF,
	A.CODIGO_REGISTRO
FROM 
(CHEF C JOIN REGISTRO A ON C.CODIGO_REGISTRO = A.CODIGO_REGISTRO)
JOIN CLASIFICACION G ON C.CODIGO_REGISTRO = G.CODIGO_REGISTRO

-- Mostrando la vista PREMIO
SELECT *
FROM PREMIO
WHERE CODIGO_REGISTRO = 1
	AND NOMBRE_CHEF = 'Laura'
	OR NOMBRE_CHEF = 'Dayron'
GROUP BY
	NOMBRE_CHEF,
	PLATO_POPULAR,
	PUESTO_CLASIF,
	CODIGO_REGISTRO

-- Agregando subconsulta
SELECT NOMBRE_CHEF, COUNT(NOMBRE_CHEF) AS CANT_CHEF
FROM PREMIO WHERE NOMBRE_CHEF IN (
	SELECT NOMBRE_CHEF FROM CHEF
)
GROUP BY NOMBRE_CHEF

-- SUBCONSULTAS

-- INSERTANDO A TRAVES DE SUBCONSULTAS
INSERT INTO CLASIFICACION (ID_CLASIFICACION, NOMBRECHEF, APELLIDO1, APELLIDO2)
SELECT ID_CHEF, NOMBRE_CHEF, APELLIDO_1, APELLIDO_2 FROM CHEF WHERE ID_CHEF = 3

-- ELIMINANDO A TRAVES DE SUBCONSULTAS
DELETE FROM CLASIFICACION WHERE
NOMBRECHEF !=(SELECT NOMBRE_CHEF FROM CHEF WHERE ID_CHEF=1)

-- UPDATE A TRAVES DE SUBCONSULTA
UPDATE REGISTRO SET INGRED_POPULAR = 'pan'
WHERE PLATO_POPULAR= (SELECT PLATO_POPULAR FROM CLASIFICACION WHERE NOMBRECHEF= 'Dayron')

SELECT * FROM CLASIFICACION